# Generated by Django 4.2.6 on 2023-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('count_skill', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ключевые навыки',
                'ordering': ('id',),
            },
        ),
    ]
