# Generated by Django 4.2.6 on 2023-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='count_skill',
            field=models.IntegerField(),
        ),
    ]
