version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=warlight123
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/mysql/data
    restart: always
  web:
    build: .
    command: python /usr/src/my_djang/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/my_djang
    ports:
      - 8001:8000
    depends_on:
      - db

volumes:
  postgres_data:
